export const CREATE_SHOPPING_CARD_PRODUCT = 'CREATE_SHOPPING_CARD_PRODUCT';
export const DELETE_SHOPPING_CARD_PRODUCT = 'DELETE_SHOPPING_CARD_PRODUCT';
export const EDIT_SHOPPING_CARD_PRODUCT = 'EDIT_SHOPPING_CARD_PRODUCT';
export const GET_SHOPPING_CARD_PRODUCT = 'GET_SHOPPING_CARD_PRODUCT';
export const GET_SHOPPING_CARD_PRODUCTS = 'GET_SHOPPING_CARD_PRODUCTS';
export const CLEAR_SHOPPING_CARD_PRODUCTS = 'CLEAR_SHOPPING_CARD_PRODUCTS';